/* ==========================================================================
   REAL PRODUCT CATALOG - Durga Furniture
   Consists ONLY of the 11 real products supplied by the user in the products/ folder.
   ========================================================================== */

const productData = [
  {
    id: 'wooden-tv-unit-premium-showcase',
    title: 'Wooden TV Unit',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_tv_unit.jpeg',
    description: 'A premium wooden TV entertainment unit designed for modern living. Features a dedicated TV mounting area, multiple open display shelves, glass-paneled decorative doors, and spacious bottom drawers and cabinets for media storage.',
    dimensions: '4 ft – Bottom / 5 ft – Bottom / 6 ft – Bottom / 6 × 6 ft – TV Unit',
    materials: 'High-Grade Engineered Wood, Polish Veneer Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Finish', 'Wenge Finish', 'Mahogany Finish']
  },
  {
    id: 'wooden-tv-unit-modern-showcase',
    title: 'Wooden TV Unit',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/Wooden TV Unit.jpeg',
    description: 'A contemporary wooden TV cabinet designed for stylish living rooms. Offers open shelving, wire management cutouts, and drawers for devices.',
    dimensions: '4 ft – Bottom / 5 ft – Bottom / 6 ft – Bottom / 6 × 6 ft – TV Unit',
    materials: 'Premium Engineered Wood, Laminate Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Finish', 'Walnut Finish', 'Wenge Finish']
  },
  {
    id: 'wooden-tv-unit-minimalist-console',
    title: 'Wooden TV Unit',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/Wooden TV Unit (2).jpeg',
    description: 'Sleek and low-profile wooden TV stand featuring minimalist aesthetics, push-to-open cabinets, and a durable surface top.',
    dimensions: '4 ft – Bottom / 5 ft – Bottom / 6 ft – Bottom / 6 × 6 ft – TV Unit',
    materials: 'High-Density Engineered Wood, Veneer Polish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Finish', 'Wenge Finish', 'Mahogany Finish']
  },
  {
    id: 'wooden-tv-unit-contemporary-credenza',
    title: 'Wooden TV Unit',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/Wooden TV Unit (3).jpeg',
    description: 'Elegant TV entertainment center featuring geometric wood panel doors, spacious internal shelves, and sturdy support legs.',
    dimensions: '4 ft – Bottom / 5 ft – Bottom / 6 ft – Bottom / 6 × 6 ft – TV Unit',
    materials: 'Premium Compressed Wood, Melamine Polish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Natural Teak', 'Classic Walnut', 'Dark Chocolate']
  },
  {
    id: 'wooden-tv-unit-luxury-cabinet',
    title: 'Wooden TV Unit',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/Wooden TV Unit (4).jpeg',
    description: 'A wall-mounted and floor-standing hybrid wooden TV showcase. Designed with LED light mounting spots and tempered glass shelves.',
    dimensions: '4 ft – Bottom / 5 ft – Bottom / 6 ft – Bottom / 6 × 6 ft – TV Unit',
    materials: 'High-Grade Engineered Wood, Glass Panels',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Polish', 'Wenge Polish', 'Rosewood Polish']
  },
  {
    id: 'wooden-tv-unit-executive-entertainment',
    title: 'Wooden TV Unit',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/Wooden TV Unit (5).jpeg',
    description: 'Spacious TV console unit built with double side cabinets, open media storage slots, and soft-closing drawer glides.',
    dimensions: '4 ft – Bottom / 5 ft – Bottom / 6 ft – Bottom / 6 × 6 ft – TV Unit',
    materials: 'Engineered Wood, High-Quality Laminate & Polish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Wood Finish', 'Walnut Wood Finish', 'Wenge Wood Finish']
  },
  {
    id: 'wooden-tv-unit-classic-royal',
    title: 'Wooden TV Unit',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/Wooden TV Unit (6).jpeg',
    description: 'Traditional style heavy wooden TV cabinet with beautiful wood grain finishes, brass handles, and robust corner posts.',
    dimensions: '4 ft – Bottom / 5 ft – Bottom / 6 ft – Bottom / 6 × 6 ft – TV Unit',
    materials: 'High-Grade Compressed Wood, Antique Polish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Antique Teak', 'Dark Walnut', 'Mahogany']
  },
  {
    id: 'wooden-computer-table-ergonomic',
    title: 'Wooden Computer Table',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_computer_table.jpeg',
    description: 'A sturdy wooden computer table with a dedicated keyboard tray, a side lockable drawer, and storage cabinet. Ideal for home office or study space.',
    dimensions: '2 × 1½ ft / 2½ × 1½ ft / 3 × 1½ ft',
    materials: 'Engineered Wood, Scratch-Resistant Melamine Laminate',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Wood Finish', 'Walnut Wood Finish', 'Wenge Wood Finish', 'Black Marble Finish']
  },
  {
    id: 'wooden-wardrobe-customized-double',
    title: 'Wooden Wardrobe',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_wardrobe.jpeg',
    description: 'A premium double-door wardrobe offering generous clothing storage. Features sturdy metal handles and a secure key-lock mechanism.',
    dimensions: '2 Door: 6½ ft × 32" × 15" / 3 Door: 6½ ft × 48" × 16"',
    materials: 'High-Density Engineered Wood, Premium Cabinet Hardware',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Finish', 'Black Copper Marble', 'Black Gold Marble']
  },
  {
    id: 'wooden-office-table-premium-4x2',
    title: 'Wooden Office Desk',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_office_table.jpeg',
    description: 'Standard 4x2 office desk with a side drawer and cabinet. Built for offices, study rooms, and workstations.',
    dimensions: '3 × 2 ft / 4 × 2 ft',
    materials: 'Heavy-Duty Compressed Wood, High-Quality Laminate',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Wenge Finish', 'Maple Finish', 'Mahogany Finish', 'Walnut Finish']
  },
  {
    id: 'wooden-dressing-table-stool-elegant',
    title: 'Wooden Dressing Table',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_dressing_table.jpeg',
    description: 'Modern compact dressing table equipped with a long vertical mirror, side shelves for cosmetics, a lockable drawer, and a matching wooden stool.',
    dimensions: 'Basic Single Mirror / Basic Single Mirror with Storage / Single Shelf Dressing Table / Double Shelf Dressing Table / Long Mirror Dressing Table / Long Mirror + Storage',
    materials: 'Engineered Wood, Premium Silver-Backed Mirror Glass',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Color', 'Mahogany Color', 'Oak Color', 'Marble Color']
  },
  {
    id: 'wooden-dressing-vanity-multi-finish',
    title: 'Wooden Dressing Table',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_dressing_vanity.jpeg',
    description: 'A premium floor-standing dressing table with multi-tier cosmetic display shelves, a wide drawer, and a matching stool.',
    dimensions: 'Basic Single Mirror / Basic Single Mirror with Storage / Single Shelf Dressing Table / Double Shelf Dressing Table / Long Mirror Dressing Table / Long Mirror + Storage',
    materials: 'Seasoned Engineered Wood, High-Definition Mirror',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Light Wood', 'Mahogany Wood', 'Teak Wood', 'Walnut Wood', 'Marble Finish']
  },
  {
    id: 'wooden-dressing-cabinet-geometric',
    title: 'Wooden Dressing Table',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_dressing_cabinet.jpeg',
    description: 'A highly decorative dressing cabinet featuring a swing full-length mirror door and modern interlocking square geometric open display shelves.',
    dimensions: 'Basic Single Mirror / Basic Single Mirror with Storage / Single Shelf Dressing Table / Double Shelf Dressing Table / Long Mirror Dressing Table / Long Mirror + Storage',
    materials: 'Heavy Engineered Wood, Premium Quality Glass Mirror',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Finish', 'Wenge Finish']
  },
  {
    id: 'wooden-pooja-mandir-premium-5ft',
    title: 'Wooden Pooja Mandir',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_pooja_mandir.jpeg',
    description: 'An ornate 5-feet tall Pooja stand featuring glass doors with beautiful frosted Ganesha motifs, dome top spikes, a pull-out drawer, and bottom storage cabinets.',
    dimensions: '4 × 2½ ft – Normal + Arch / 4 × 2½ ft – Glass + Arch / 5 × 3 ft – Normal + Kalasam / 5 × 3 ft – Glass + Kalasam / 5 × 3 ft – Normal + Arch / 5 × 3 ft – Glass + Arch',
    materials: 'Solid Seasoned Wood Structure, Frosted Glass Panels',
    warranty: '2 Years Structural Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Wood', 'Walnut Wood', 'Mahogany Wood', 'Wenge Wood', 'Beech Wood']
  },
  {
    id: 'wooden-pooja-mandir-classic-arch',
    title: 'Wooden Pooja Mandir',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 6.58.02 PM.jpeg',
    description: 'A beautifully designed wooden Pooja mandir featuring classical arch designs, integrated drawer space, and custom wood paneling.',
    dimensions: '4 × 2½ ft – Normal + Arch / 4 × 2½ ft – Glass + Arch / 5 × 3 ft – Normal + Kalasam / 5 × 3 ft – Glass + Kalasam / 5 × 3 ft – Normal + Arch / 5 × 3 ft – Glass + Arch',
    materials: 'Solid Seasoned Wood Structure, Frosted Glass Panels',
    warranty: '2 Years Structural Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Wood', 'Walnut Wood', 'Mahogany Wood', 'Wenge Wood', 'Beech Wood']
  },
  {
    id: 'wooden-cot-lattice-teak',
    title: 'Wooden Cot',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_cot_lattice.jpeg',
    description: 'Elegantly crafted double bed cot made from high-quality seasoned teak wood. Features a classic lattice cutout pattern on the headboard and footboard, and a polished wood plank surface.',
    dimensions: '75" × 36" – Single / 75" × 48" – Double / 75" × 60" – Queen / 75" × 72" – King',
    materials: 'Seasoned Solid Teak Wood',
    warranty: '5 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: ['Single (75" × 36")', 'Double (75" × 48")', 'Queen (75" × 60")', 'King (75" × 72")'],
    mattressOptions: ['Without Mattress', 'With Foam Mattress', 'With Spring Mattress', 'With Orthopedic Mattress'],
    finishOptions: ['Natural Polish Teak', 'Walnut', 'Mahogany', 'Rosewood']
  },
  {
    id: 'wooden-cot-checkerboard-solid',
    title: 'Wooden Cot',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_cot_checkerboard.jpeg',
    description: 'Sturdy double cot featuring a modern weave/checkerboard block texture on both the headboard and footboard. High-durability polish emphasizes the natural wood grains.',
    dimensions: '75" × 36" – Single / 75" × 48" – Double / 75" × 60" – Queen / 75" × 72" – King',
    materials: 'Premium Solid Seasoned Wood',
    warranty: '5 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: ['Single (75" × 36")', 'Double (75" × 48")', 'Queen (75" × 60")', 'King (75" × 72")'],
    mattressOptions: ['Without Mattress', 'With Foam Mattress', 'With Spring Mattress', 'With Orthopedic Mattress'],
    finishOptions: ['Natural Polish Teak', 'Walnut', 'Mahogany', 'Rosewood']
  },
  {
    id: 'wooden-cot-series-premium-teak',
    title: 'Wooden Cot',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_cot_series.jpeg',
    description: 'A versatile teak wood cot available in multiple sizes and headboard designs (including carving, check-weave, and horizontal slats).',
    dimensions: '75" × 36" – Single / 75" × 48" – Double / 75" × 60" – Queen / 75" × 72" – King',
    materials: 'Solid Teak Wood',
    warranty: '5 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: ['Single (75" × 36")', 'Double (75" × 48")', 'Queen (75" × 60")', 'King (75" × 72")'],
    mattressOptions: ['Without Mattress', 'With Foam Mattress', 'With Spring Mattress', 'With Orthopedic Mattress'],
    finishOptions: ['Natural Polish Teak', 'Walnut', 'Mahogany', 'Rosewood']
  },
  {
    id: 'wooden-cot-modern-headboard',
    title: 'Wooden Cot',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 6.57.38 PM.jpeg',
    description: 'A modern design wooden cot crafted with a solid headboard and premium seasoning to prevent warping. Provides excellent support and aesthetics.',
    dimensions: '75" × 36" – Single / 75" × 48" – Double / 75" × 60" – Queen / 75" × 72" – King',
    materials: 'Premium Solid Seasoned Wood',
    warranty: '5 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: ['Single (75" × 36")', 'Double (75" × 48")', 'Queen (75" × 60")', 'King (75" × 72")'],
    mattressOptions: ['Without Mattress', 'With Foam Mattress', 'With Spring Mattress', 'With Orthopedic Mattress'],
    finishOptions: ['Natural Polish Teak', 'Walnut', 'Mahogany', 'Rosewood']
  },
  {
    id: 'wooden-cot-classic-carved',
    title: 'Wooden Cot',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 6.57.38 PM (1).jpeg',
    description: 'Beautifully carved classic wooden cot featuring traditional headboard patterns and a solid build structure for maximum comfort.',
    dimensions: '75" × 36" – Single / 75" × 48" – Double / 75" × 60" – Queen / 75" × 72" – King',
    materials: 'Premium Solid Seasoned Wood',
    warranty: '5 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: ['Single (75" × 36")', 'Double (75" × 48")', 'Queen (75" × 60")', 'King (75" × 72")'],
    mattressOptions: ['Without Mattress', 'With Foam Mattress', 'With Spring Mattress', 'With Orthopedic Mattress'],
    finishOptions: ['Natural Polish Teak', 'Walnut', 'Mahogany', 'Rosewood']
  },
  {
    id: 'wooden-cot-slat-minimalist',
    title: 'Wooden Cot',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 6.57.38 PM (2).jpeg',
    description: 'Minimalist wooden bed frame featuring horizontal slat details and high-strength leg supports, ideal for modern bedrooms.',
    dimensions: '75" × 36" – Single / 75" × 48" – Double / 75" × 60" – Queen / 75" × 72" – King',
    materials: 'Premium Solid Seasoned Wood',
    warranty: '5 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: ['Single (75" × 36")', 'Double (75" × 48")', 'Queen (75" × 60")', 'King (75" × 72")'],
    mattressOptions: ['Without Mattress', 'With Foam Mattress', 'With Spring Mattress', 'With Orthopedic Mattress'],
    finishOptions: ['Natural Polish Teak', 'Walnut', 'Mahogany', 'Rosewood']
  },
  {
    id: 'wooden-cot-traditional-royal',
    title: 'Wooden Cot',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 6.57.39 PM.jpeg',
    description: 'A grand royal-style wooden cot with ornamental post accents, showcasing rich grains and a luxurious lacquer finish.',
    dimensions: '75" × 36" – Single / 75" × 48" – Double / 75" × 60" – Queen / 75" × 72" – King',
    materials: 'Premium Solid Seasoned Wood',
    warranty: '5 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: ['Single (75" × 36")', 'Double (75" × 48")', 'Queen (75" × 60")', 'King (75" × 72")'],
    mattressOptions: ['Without Mattress', 'With Foam Mattress', 'With Spring Mattress', 'With Orthopedic Mattress'],
    finishOptions: ['Natural Polish Teak', 'Walnut', 'Mahogany', 'Rosewood']
  },
  {
    id: 'wooden-cot-sleek-contemporary',
    title: 'Wooden Cot',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 8.17.13 PM.jpeg',
    description: 'A contemporary double wooden cot offering clean lines, low floor profile, and noise-free heavy-duty inner frame.',
    dimensions: '75" × 36" – Single / 75" × 48" – Double / 75" × 60" – Queen / 75" × 72" – King',
    materials: 'Premium Solid Seasoned Wood',
    warranty: '5 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: ['Single (75" × 36")', 'Double (75" × 48")', 'Queen (75" × 60")', 'King (75" × 72")'],
    mattressOptions: ['Without Mattress', 'With Foam Mattress', 'With Spring Mattress', 'With Orthopedic Mattress'],
    finishOptions: ['Natural Polish Teak', 'Walnut', 'Mahogany', 'Rosewood']
  },
  {
    id: 'wooden-cot-panel-comfort',
    title: 'Wooden Cot',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 8.17.22 PM.jpeg',
    description: 'Sturdy panel wooden bed featuring an elegant block border headboard and a highly durable support structure.',
    dimensions: '75" × 36" – Single / 75" × 48" – Double / 75" × 60" – Queen / 75" × 72" – King',
    materials: 'Premium Solid Seasoned Wood',
    warranty: '5 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: ['Single (75" × 36")', 'Double (75" × 48")', 'Queen (75" × 60")', 'King (75" × 72")'],
    mattressOptions: ['Without Mattress', 'With Foam Mattress', 'With Spring Mattress', 'With Orthopedic Mattress'],
    finishOptions: ['Natural Polish Teak', 'Walnut', 'Mahogany', 'Rosewood']
  },
  {
    id: 'wooden-office-workstation-modular',
    title: 'Wooden Office Desk',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_office_workstation.jpeg',
    description: 'A modular double-sided linear workstation desk featuring thick wood laminate table tops with wire managers and a solid black powder-coated steel loop frame. Ideal for offices and co-working spaces.',
    dimensions: '6 ft L x 4 ft W x 2.5 ft H',
    materials: 'Pre-Laminated Particle Board, Powder Coated Steel Frame',
    warranty: '1 Year Structural Warranty',
    availability: 'In Stock',
    finishOptions: ['Natural Teak / Black Frame', 'Oak / White Frame', 'Walnut / Black Frame']
  },
  {
    id: 'wooden-office-desk-double-pedestal',
    title: 'Wooden Office Desk',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_office_desk_double_pedestal.jpeg',
    description: 'A premium office desk featuring a spacious wood laminate top and two secure key-locked steel drawer cabinets. One pedestal holds 2 deep drawers, and the other holds 3 utility drawers.',
    dimensions: '5 ft W x 2.5 ft D x 2.5 ft H',
    materials: 'Laminated Wooden Top, Powder Coated Steel Pedestals',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Laminate / Grey Pedestals', 'Walnut Laminate / Black Pedestals']
  },
  {
    id: 'wooden-study-desk-blue-pedestal',
    title: 'Wooden Study Desk',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_study_desk_blue_pedestal.jpeg',
    description: 'A compact study and office table featuring a light wood laminate top and a secure lockable blue steel 2-drawer pedestal unit on the right. Perfect for children study rooms and office setups.',
    dimensions: '4 ft W x 2 ft D x 2.5 ft H',
    materials: 'Maple Laminate Board, Steel Legs & Drawers',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Maple Top / Blue Pedestal', 'Oak Top / Grey Pedestal']
  },
  {
    id: 'wooden-desk-angled-legs',
    title: 'Wooden Study Desk',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_desk_angled_legs.jpeg',
    description: 'A minimalist modern writing desk designed with a warm wood laminate top and sleek, angled black powder-coated metal loop legs. Sturdy structural frame adds a contemporary look to any workspace.',
    dimensions: '4 ft W x 2 ft D x 2.5 ft H',
    materials: 'High-Quality Engineered Wood, Powder Coated Metal Legs',
    warranty: '1 Year Structural Warranty',
    availability: 'In Stock',
    finishOptions: ['Teak Wood Top / Black Legs', 'Walnut Top / Black Legs']
  },
  {
    id: 'wooden-dining-table-premium',
    title: 'Wooden Dinning Table',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/Wooden Dinning Table.jpeg',
    description: 'A premium wooden dining table set designed for family dining and elegance. Available in different wood finishes and distinct designs to suit your dining room decor.',
    dimensions: '4 × 2½ ft – 4 Chairs / 5 × 3 ft – 4 Chairs / 6 × 3 ft – 6 Chairs / 6½ × 3½ ft – 6 Chairs',
    materials: 'Premium Solid Seasoned Wood',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    series: '7',
    finishOptions: ['Natural Teak Finish', 'Warm Walnut Finish', 'Dark Mahogany Finish']
  },
  {
    id: 'wooden-sofa-premium-set',
    title: 'Wooden Sofa',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 8.37.39 PM.jpeg',
    description: 'A premium wooden sofa set handcrafted from seasoned solid teak wood. Includes comfortable cushions with premium upholstery and ergonomic armrests.',
    dimensions: '3 Seater / 5 Seater (3+1+1) / 5 Seater (3+2) / 6 Seater (3+2+1)',
    materials: 'Premium Solid Teak Wood Structure, High-Density Cushion Foam',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    series: '8',
    finishOptions: ['Teak Polish', 'Walnut Polish', 'Mahogany Polish', 'Rosewood Polish']
  },
  {
    id: 'wooden-sofa-modern-slat',
    title: 'Wooden Sofa',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 8.37.40 PM.jpeg',
    description: 'Modern style wooden sofa featuring vertical slat backrest design and sleek tapered legs for a contemporary living room look.',
    dimensions: '3 Seater / 5 Seater (3+1+1) / 5 Seater (3+2) / 6 Seater (3+2+1)',
    materials: 'Premium Solid Teak Wood Structure, High-Density Cushion Foam',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    series: '8',
    finishOptions: ['Teak Polish', 'Walnut Polish', 'Mahogany Polish', 'Rosewood Polish']
  },
  {
    id: 'wooden-sofa-classic-carved',
    title: 'Wooden Sofa',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 8.37.40 PM (1).jpeg',
    description: 'Traditional style wooden sofa with elegant floral carvings on the crown and armrests, highlighting natural teak grains.',
    dimensions: '3 Seater / 5 Seater (3+1+1) / 5 Seater (3+2) / 6 Seater (3+2+1)',
    materials: 'Premium Solid Teak Wood Structure, High-Density Cushion Foam',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    series: '8',
    finishOptions: ['Teak Polish', 'Walnut Polish', 'Mahogany Polish', 'Rosewood Polish']
  },
  {
    id: 'wooden-sofa-contemporary-cushion',
    title: 'Wooden Sofa',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 8.37.40 PM (2).jpeg',
    description: 'Sleek wooden sofa set designed with deep seating comfort, thick foam cushions, and low-profile modern wood frame.',
    dimensions: '3 Seater / 5 Seater (3+1+1) / 5 Seater (3+2) / 6 Seater (3+2+1)',
    materials: 'Premium Solid Teak Wood Structure, High-Density Cushion Foam',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    series: '8',
    finishOptions: ['Teak Polish', 'Walnut Polish', 'Mahogany Polish', 'Rosewood Polish']
  },
  {
    id: 'wooden-sofa-royal-maharaja',
    title: 'Wooden Sofa',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 8.42.42 PM.jpeg',
    description: 'A royal maharaja style heavy wooden sofa with curved armrests, glossy polish finish, and dense velvet cushions.',
    dimensions: '3 Seater / 5 Seater (3+1+1) / 5 Seater (3+2) / 6 Seater (3+2+1)',
    materials: 'Premium Solid Teak Wood Structure, High-Density Cushion Foam',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    series: '8',
    finishOptions: ['Teak Polish', 'Walnut Polish', 'Mahogany Polish', 'Rosewood Polish']
  },
  {
    id: 'wooden-sofa-minimalist-chic',
    title: 'Wooden Sofa',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 8.42.42 PM (1).jpeg',
    description: 'Minimalist wooden sofa set with clean geometric design lines, ideal for compact apartments and modern living spaces.',
    dimensions: '3 Seater / 5 Seater (3+1+1) / 5 Seater (3+2) / 6 Seater (3+2+1)',
    materials: 'Premium Solid Teak Wood Structure, High-Density Cushion Foam',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    series: '8',
    finishOptions: ['Teak Polish', 'Walnut Polish', 'Mahogany Polish', 'Rosewood Polish']
  },
  {
    id: 'wooden-sofa-traditional-box',
    title: 'Wooden Sofa',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 8.42.42 PM (2).jpeg',
    description: 'Sturdy box-type wooden sofa offering integrated side magazine pockets and spacious bottom storage compartments.',
    dimensions: '3 Seater / 5 Seater (3+1+1) / 5 Seater (3+2) / 6 Seater (3+2+1)',
    materials: 'Premium Solid Teak Wood Structure, High-Density Cushion Foam',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    series: '8',
    finishOptions: ['Teak Polish', 'Walnut Polish', 'Mahogany Polish', 'Rosewood Polish']
  },
  {
    id: 'wooden-sofa-luxury-lounge',
    title: 'Wooden Sofa',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/WhatsApp Image 2026-07-21 at 8.43.36 PM.jpeg',
    description: 'Luxury lounge wooden sofa set with extended corner chaise, premium textured fabrics, and reinforced hardwood frame.',
    dimensions: '3 Seater / 5 Seater (3+1+1) / 5 Seater (3+2) / 6 Seater (3+2+1)',
    materials: 'Premium Solid Teak Wood Structure, High-Density Cushion Foam',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    series: '8',
    finishOptions: ['Teak Polish', 'Walnut Polish', 'Mahogany Polish', 'Rosewood Polish']
  },
  {
    id: 'steel-bookshelf-premium',
    title: 'Steel Bookshelf',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_bookshelf.jpeg',
    description: 'A premium 4-compartment steel bookshelf with glass swing-up shutters. Features independent locking for each compartment, perfect for offices, libraries, or home study rooms.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'High-Grade Cold Rolled Steel, Powder Coated Finish, Glass Shutters',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Gloss Door: 36" x 19" x 6.5 ft (Heavy)',
      'Gloss Door: 42" x 19" x 6.5 ft (Heavy)',
      'Gloss Door: 36" x 19" x 5.5 ft (Heavy)'
    ],
    finishOptions: ['White and Blue Duo-tone']
  },
  {
    id: 'steel-stool-heavy-duty-collection',
    title: 'Steel Stool',
    category: 'Other Furniture',
    badge: 'badge-other',
    image: 'products/steel/steel_stool_collection.jpeg',
    description: 'A versatile set of heavy-duty steel stools available in multiple heights. Features a sturdy steel frame with pattern tops (newspaper print or black marble style).',
    dimensions: 'Executive Table: 4.5 × 2.5 ft | Heavy Table: 4 × 2 ft / 3 × 2 ft | Medium Table: 4 × 2 ft / 3 × 2 ft / 3 × 1½ ft | Plain Table: 4 × 2 ft / 3 × 2 ft',
    materials: 'Reinforced Steel Pipe Frame, Laminated Top',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: ['0.75 Ft', '1 Ft', '1.75 Ft', '2 Ft', '2.5 Ft', '3 Ft', '4 Ft', '5 Ft', '6 Ft'],
    finishOptions: ['Newspaper Pattern Top', 'Black Marble Top']
  },
  {
    id: 'other-office-table-series3',
    title: 'Plastic Chair',
    category: 'Other Furniture',
    badge: 'badge-other',
    image: 'products/WhatsApp Image 2026-07-19 at 9.34.14 PM.jpeg',
    description: 'A practical plastic chair designed for compact spaces and everyday use. Clean, lightweight, and easy to place in homes, offices, or waiting areas.',
    materials: 'High-Quality Plastic',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    series: '3',
    finishOptions: ['Teak', 'Walnut', 'Mahogany']
  },
  {
    id: 'steel-almirah-4door-grey',
    title: 'Steel Almirah',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_almirah_grey.jpeg',
    description: 'A spacious 6-feet tall steel almirah featuring a 4-door compartment layout with a secure multi-point lock. Built with premium heavy-duty steel for maximum security.',
    dimensions: 'Heavy: 42" × 19" × 6½ ft (75kg) / 36" × 19" × 6½ ft (63kg) | Medium: 42" × 19" × 6½ ft (65kg) / 36" × 19" × 6½ ft (52kg) | Lite: 34" × 17" × 6.6 ft (40kg) / 34" × 17" × 5½ ft (35kg) / 34" × 15" × 5½ ft (33kg) | 3-Door: 48" × 6½ ft / 60" × 6½ ft (90kg-110kg)',
    materials: 'Heavy Gauge Cold Rolled Steel, Powder Coated Finish',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Heavy: 42" x 19" x 6.5 ft (75kg)',
      'Heavy: 36" x 19" x 6.5 ft (63kg)',
      'Medium: 42" x 19" x 6.5 ft (65kg)',
      'Medium: 36" x 19" x 6.5 ft (52kg)',
      'Lite: 34" x 17" x 6.5 ft (40kg)',
      'Lite: 34" x 17" x 5.5 ft (35kg)',
      'Lite: 34" x 15" x 5.5 ft (33kg)'
    ],
    finishOptions: ['Classic Grey']
  },
  {
    id: 'steel-almirah-4door-rose',
    title: 'Steel Almirah',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_almirah_rose.jpeg',
    description: 'A vibrant rose/pink color 6-feet tall steel almirah featuring a 4-door compartment layout. Dust and rust-proof coating ensures a long-lasting, glossy finish.',
    dimensions: 'Heavy: 42" × 19" × 6½ ft (75kg) / 36" × 19" × 6½ ft (63kg) | Medium: 42" × 19" × 6½ ft (65kg) / 36" × 19" × 6½ ft (52kg) | Lite: 34" × 17" × 6.6 ft (40kg) / 34" × 17" × 5½ ft (35kg) / 34" × 15" × 5½ ft (33kg) | 3-Door: 48" × 6½ ft / 60" × 6½ ft (90kg-110kg)',
    materials: 'Heavy Gauge Cold Rolled Steel, Glossy Powder Coated Finish',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Heavy: 42" x 19" x 6.5 ft (75kg)',
      'Heavy: 36" x 19" x 6.5 ft (63kg)',
      'Medium: 42" x 19" x 6.5 ft (65kg)',
      'Medium: 36" x 19" x 6.5 ft (52kg)',
      'Lite: 34" x 17" x 6.5 ft (40kg)',
      'Lite: 34" x 17" x 5.5 ft (35kg)',
      'Lite: 34" x 15" x 5.5 ft (33kg)'
    ],
    finishOptions: ['Rose Pink']
  },
  {
    id: 'steel-showcase-almirah-mirror',
    title: 'Steel Almirah',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_showcase_almirah.jpeg',
    description: 'An elegant dressing wardrobe featuring a full-length mirror door on the left and a lockable door with a frosted glass floral pattern on the right. Includes a bottom lockable drawer.',
    dimensions: 'Heavy: 42" × 19" × 6½ ft (75kg) / 36" × 19" × 6½ ft (63kg) | Medium: 42" × 19" × 6½ ft (65kg) / 36" × 19" × 6½ ft (52kg) | Lite: 34" × 17" × 6.6 ft (40kg) / 34" × 17" × 5½ ft (35kg) / 34" × 15" × 5½ ft (33kg) | 3-Door: 48" × 6½ ft / 60" × 6½ ft (90kg-110kg)',
    materials: 'Seasoned Cold Rolled Steel, Decorative Frosted Glass, Silver-Backed Mirror',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Heavy: 42" x 19" x 6.5 ft (75kg)',
      'Heavy: 36" x 19" x 6.5 ft (63kg)',
      'Medium: 42" x 19" x 6.5 ft (65kg)',
      'Medium: 36" x 19" x 6.5 ft (52kg)',
      'Lite: 34" x 17" x 6.5 ft (40kg)',
      'Lite: 34" x 17" x 5.5 ft (35kg)',
      'Lite: 34" x 15" x 5.5 ft (33kg)'
    ],
    finishOptions: ['Dark Brown', 'Black', 'Walnut Brown', 'Beige', 'Grey', 'Chocolate Brown']
  },
  {
    id: 'steel-almirah-purple-mirror',
    title: 'Steel Almirah',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_almirah_purple_mirror.jpeg',
    description: 'A premium double-door steel wardrobe finished in a striking purple coat. Left door is equipped with a beautiful arched vanity mirror. Offers extensive shelf storage and secure locks.',
    dimensions: 'Heavy: 42" × 19" × 6½ ft (75kg) / 36" × 19" × 6½ ft (63kg) | Medium: 42" × 19" × 6½ ft (65kg) / 36" × 19" × 6½ ft (52kg) | Lite: 34" × 17" × 6.6 ft (40kg) / 34" × 17" × 5½ ft (35kg) / 34" × 15" × 5½ ft (33kg) | 3-Door: 48" × 6½ ft / 60" × 6½ ft (90kg-110kg)',
    materials: 'Heavy-Duty Cold Rolled Steel, Powder Coated Finish',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Heavy: 42" x 19" x 6.5 ft (75kg)',
      'Heavy: 36" x 19" x 6.5 ft (63kg)',
      'Medium: 42" x 19" x 6.5 ft (65kg)',
      'Medium: 36" x 19" x 6.5 ft (52kg)',
      'Lite: 34" x 17" x 6.5 ft (40kg)',
      'Lite: 34" x 17" x 5.5 ft (35kg)',
      'Lite: 34" x 15" x 5.5 ft (33kg)'
    ],
    finishOptions: ['Vibrant Purple', 'Classic Blue', 'Rose Pink']
  },
  {
    id: 'steel-almirah-orange-locker',
    title: 'Steel Locker',
    category: 'Other Furniture',
    badge: 'badge-other',
    image: 'products/steel/steel_almirah_orange_locker.jpeg',
    description: 'A heavy-duty three-shutter steel wardrobe. The central shutter features a modern diamond cutout design. The open compartments show a multi-shelf configuration and a built-in lockable safe locker with Ganesha motif.',
    dimensions: 'Heavy: 42" × 19" × 6½ ft (75kg) / 36" × 19" × 6½ ft (63kg) | Medium: 42" × 19" × 6½ ft (65kg) / 36" × 19" × 6½ ft (52kg) | Lite: 34" × 17" × 6.6 ft (40kg) / 34" × 17" × 5½ ft (35kg) / 34" × 15" × 5½ ft (33kg) | 3-Door: 48" × 6½ ft / 60" × 6½ ft (90kg-110kg)',
    materials: 'Heavy Gauge Structural Steel, Laminated Powder Coat',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Heavy: 42" x 19" x 6.5 ft (75kg)',
      'Heavy: 36" x 19" x 6.5 ft (63kg)',
      'Medium: 42" x 19" x 6.5 ft (65kg)',
      'Medium: 36" x 19" x 6.5 ft (52kg)',
      'Lite: 34" x 17" x 6.5 ft (40kg)',
      'Lite: 34" x 17" x 5.5 ft (35kg)',
      'Lite: 34" x 15" x 5.5 ft (33kg)'
    ],
    finishOptions: ['Lava Orange', 'Olive Green', 'Royal Blue']
  },
  {
    id: 'steel-almirah-blue-double',
    title: 'Steel Almirah',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_almirah_blue_double.jpeg',
    description: 'A versatile double-door steel almirah featuring a multi-shelf layout, an internal lockable locker safe at the top left, and a dedicated hanging space on the right side with a lockable drawer.',
    dimensions: 'Heavy: 42" × 19" × 6½ ft (75kg) / 36" × 19" × 6½ ft (63kg) | Medium: 42" × 19" × 6½ ft (65kg) / 36" × 19" × 6½ ft (52kg) | Lite: 34" × 17" × 6.6 ft (40kg) / 34" × 17" × 5½ ft (35kg) / 34" × 15" × 5½ ft (33kg) | 3-Door: 48" × 6½ ft / 60" × 6½ ft (90kg-110kg)',
    materials: 'Cold Rolled Steel Sheet, High-Gloss Paint Finish',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Heavy: 42" x 19" x 6.5 ft (75kg)',
      'Heavy: 36" x 19" x 6.5 ft (63kg)',
      'Medium: 42" x 19" x 6.5 ft (65kg)',
      'Medium: 36" x 19" x 6.5 ft (52kg)',
      'Lite: 34" x 17" x 6.5 ft (40kg)',
      'Lite: 34" x 17" x 5.5 ft (35kg)',
      'Lite: 34" x 15" x 5.5 ft (33kg)'
    ],
    finishOptions: ['Royal Blue', 'Dark Chocolate', 'Maroon']
  },
  {
    id: 'steel-almirah-wine-single',
    title: 'Steel Almirah',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_almirah_wine_single.jpeg',
    description: 'A compact and space-saving single-door steel cupboard. Opens to reveal 5 tall storage shelves, perfect for narrow spaces, home storage, or files in offices.',
    dimensions: 'Heavy: 42" × 19" × 6½ ft (75kg) / 36" × 19" × 6½ ft (63kg) | Medium: 42" × 19" × 6½ ft (65kg) / 36" × 19" × 6½ ft (52kg) | Lite: 34" × 17" × 6.6 ft (40kg) / 34" × 17" × 5½ ft (35kg) / 34" × 15" × 5½ ft (33kg) | 3-Door: 48" × 6½ ft / 60" × 6½ ft (90kg-110kg)',
    materials: 'High-Strength Sheet Metal, Protective Coating',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Lite: 2\' x 6.5\' (24" x 78")'
    ],
    finishOptions: ['Wine Red', 'Slate Grey', 'Ivory White']
  },
  {
    id: 'steel-cot-ornate-marble',
    title: 'Steel Cot',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_cot_ornate_marble.jpeg',
    description: 'An elegant steel double cot featuring a sturdy dark mahogany brown frame. The bed board is laminated in a beautiful brown-and-white marble texture print. The headboard has lovely classic scrollwork patterns.',
    dimensions: 'Square Cot: 4 ft / 5 ft / 6 ft | Aarch / Ordinary Cot: 4 ft (Heavy & Medium) | Standard Cot: 42" (Heavy & Medium) / 44" (Heavy) | Single Cot: 36" (Heavy & Medium) / 30" (Heavy & Medium) | Bunker Cot: 2.5 ft (Heavy) / 3 ft (Heavy)',
    materials: 'Reinforced Tubular Steel Frame, Textured Laminated Board',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Square Cot - 4 ft width',
      'Square Cot - 5 ft width',
      'Square Cot - 6 ft width',
      'Aarch Cot - 4 ft width (Heavy)',
      'Aarch Cot - 4 ft width (Medium)',
      'Ordinary Cot - 4 ft width (Heavy)',
      'Ordinary Cot - 4 ft width (Medium)',
      'Cot - 42" width (Heavy)',
      'Cot - 42" width (Medium)',
      'Cot - 44" width (Heavy)',
      'Heavy Cot - 36" width (Heavy)',
      'Heavy Cot - 36" width (Medium)',
      'Steel Cot - 30" width (Heavy)',
      'Steel Cot - 30" width (Medium)',
      'Bunker Cot - 2.5 ft width (Heavy)',
      'Bunker Cot - 3 ft width (Heavy)'
    ],
    mattressOptions: ['Without Mattress', 'With Foam Mattress', 'With Coir Mattress'],
    finishOptions: ['Brown Marble Print', 'Black Marble Print']
  },
  {
    id: 'steel-cot-minimalist-black',
    title: 'Steel Cot',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_cot_minimalist_black.jpeg',
    description: 'A sleek, matte black steel cot designed with a modern geometric block pattern headboard. Extra reinforced center supports guarantee zero creaking and lifetime structural stability.',
    dimensions: 'Square Cot: 4 ft / 5 ft / 6 ft | Aarch / Ordinary Cot: 4 ft (Heavy & Medium) | Standard Cot: 42" (Heavy & Medium) / 44" (Heavy) | Single Cot: 36" (Heavy & Medium) / 30" (Heavy & Medium) | Bunker Cot: 2.5 ft (Heavy) / 3 ft (Heavy)',
    materials: 'Heavy-Duty Square Steel Tubing, Powder Coated Matte Finish',
    warranty: '5 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Square Cot - 4 ft width',
      'Square Cot - 5 ft width',
      'Square Cot - 6 ft width',
      'Aarch Cot - 4 ft width (Heavy)',
      'Aarch Cot - 4 ft width (Medium)',
      'Ordinary Cot - 4 ft width (Heavy)',
      'Ordinary Cot - 4 ft width (Medium)',
      'Cot - 42" width (Heavy)',
      'Cot - 42" width (Medium)',
      'Cot - 44" width (Heavy)',
      'Heavy Cot - 36" width (Heavy)',
      'Heavy Cot - 36" width (Medium)',
      'Steel Cot - 30" width (Heavy)',
      'Steel Cot - 30" width (Medium)',
      'Bunker Cot - 2.5 ft width (Heavy)',
      'Bunker Cot - 3 ft width (Heavy)'
    ],
    mattressOptions: ['Without Mattress', 'With Foam Mattress', 'With Orthopedic Mattress'],
    finishOptions: ['Matte Black', 'Dark Grey', 'Teak Wood-tone Posts']
  },
  {
    id: 'steel-cot-ornate-blue',
    title: 'Steel Cot',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_cot_ornate_blue.jpeg',
    description: 'A striking steel double cot featuring a high-gloss royal blue headboard pattern and bed surface. The headboard is designed with elegant floral and leaf metal carvings.',
    dimensions: 'Square Cot: 4 ft / 5 ft / 6 ft | Aarch / Ordinary Cot: 4 ft (Heavy & Medium) | Standard Cot: 42" (Heavy & Medium) / 44" (Heavy) | Single Cot: 36" (Heavy & Medium) / 30" (Heavy & Medium) | Bunker Cot: 2.5 ft (Heavy) / 3 ft (Heavy)',
    materials: 'High-Grade Tubular Steel, Glossy Powder Coated Finish',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Square Cot - 4 ft width',
      'Square Cot - 5 ft width',
      'Square Cot - 6 ft width',
      'Aarch Cot - 4 ft width (Heavy)',
      'Aarch Cot - 4 ft width (Medium)',
      'Ordinary Cot - 4 ft width (Heavy)',
      'Ordinary Cot - 4 ft width (Medium)',
      'Cot - 42" width (Heavy)',
      'Cot - 42" width (Medium)',
      'Cot - 44" width (Heavy)',
      'Heavy Cot - 36" width (Heavy)',
      'Heavy Cot - 36" width (Medium)',
      'Steel Cot - 30" width (Heavy)',
      'Steel Cot - 30" width (Medium)',
      'Bunker Cot - 2.5 ft width (Heavy)',
      'Bunker Cot - 3 ft width (Heavy)'
    ],
    mattressOptions: ['Without Mattress', 'With Foam Mattress'],
    finishOptions: ['Royal Blue Gloss', 'Crimson Red Gloss']
  },
  {
    id: 'steel-cot-triple-circle',
    title: 'Steel Cot',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_cot_triple_circle.jpeg',
    description: 'A sturdy steel double cot in a matte black finish. The headboard stands out with three circular steel plates in a scroll frame and elegant gold finials at the corner posts.',
    dimensions: 'Square Cot: 4 ft / 5 ft / 6 ft | Aarch / Ordinary Cot: 4 ft (Heavy & Medium) | Standard Cot: 42" (Heavy & Medium) / 44" (Heavy) | Single Cot: 36" (Heavy & Medium) / 30" (Heavy & Medium) | Bunker Cot: 2.5 ft (Heavy) / 3 ft (Heavy)',
    materials: 'Tubular Steel Frame, Gold Painted Accents',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Square Cot - 4 ft width',
      'Square Cot - 5 ft width',
      'Square Cot - 6 ft width',
      'Aarch Cot - 4 ft width (Heavy)',
      'Aarch Cot - 4 ft width (Medium)',
      'Ordinary Cot - 4 ft width (Heavy)',
      'Ordinary Cot - 4 ft width (Medium)',
      'Cot - 42" width (Heavy)',
      'Cot - 42" width (Medium)',
      'Cot - 44" width (Heavy)',
      'Heavy Cot - 36" width (Heavy)',
      'Heavy Cot - 36" width (Medium)',
      'Steel Cot - 30" width (Heavy)',
      'Steel Cot - 30" width (Medium)',
      'Bunker Cot - 2.5 ft width (Heavy)',
      'Bunker Cot - 3 ft width (Heavy)'
    ],
    mattressOptions: ['Without Mattress', 'With Orthopedic Mattress'],
    finishOptions: ['Matte Black & Gold']
  },
  {
    id: 'steel-table-double-pedestal',
    title: 'Steel Desk',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_table_double_pedestal.jpeg',
    description: 'A premium steel office table featuring a thick wood laminate top and two lockable drawer units: one side features two deep file drawers, and the other side features three utility drawers.',
    dimensions: 'Executive Table: 4.5 × 2.5 ft | Heavy Table: 4 × 2 ft / 3 × 2 ft | Medium Table: 4 × 2 ft / 3 × 2 ft / 3 × 1½ ft | Plain Table: 4 × 2 ft / 3 × 2 ft',
    materials: 'Commercial-Grade Steel Frame, Laminated MDF Top',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Executive Table - 4.5 x 2.5 ft',
      'Heavy Table - 4 x 2 ft',
      'Heavy Table - 3 x 2 ft',
      'Medium Table - 4 x 2 ft',
      'Medium Table - 3 x 2 ft',
      'Medium Table - 3 x 1.5 ft',
      'Plain Steel Table - 4 x 2 ft',
      'Plain Steel Table - 3 x 2 ft'
    ],
    finishOptions: ['Teak Laminate / Grey Frame', 'Walnut Laminate / Black Frame']
  },
  {
    id: 'steel-rack-5tier-grey',
    title: 'Steel Rack',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_rack_5tier_grey.jpeg',
    description: 'Commercial-grade slotted angle steel rack with 5 fully adjustable shelving levels. Ideal for warehouse storage, shops, offices, pantries, or home archives.',
    dimensions: 'Tray Rack: 3 × 1¾ ft / 3 × 1 ft / 4 × 1¾ ft / 4 × 1 ft (Heavy & Medium) | Slotted Angle Rack: 1 ft to 8 ft height (Heavy & Medium)',
    materials: 'Heavy-Duty Slotted Steel Angles, Bolted Assembly',
    warranty: '1 Year Structural Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Tray: 3 x 1.75 ft (Heavy)',
      'Tray: 3 x 1.75 ft (Medium)',
      'Tray: 3 x 1 ft (Heavy)',
      'Tray: 3 x 1 ft (Medium)',
      'Tray: 4 x 1.75 ft (Heavy)',
      'Tray: 4 x 1.75 ft (Medium)',
      'Tray: 4 x 1 ft (Heavy)',
      'Tray: 4 x 1 ft (Medium)',
      'Angle: 1 ft (Heavy)',
      'Angle: 1 ft (Medium)',
      'Angle: 2 ft (Heavy)',
      'Angle: 2 ft (Medium)',
      'Angle: 3 ft (Heavy)',
      'Angle: 3 ft (Medium)',
      'Angle: 4 ft (Heavy)',
      'Angle: 4 ft (Medium)',
      'Angle: 5 ft (Heavy)',
      'Angle: 5 ft (Medium)',
      'Angle: 6 ft (Heavy)',
      'Angle: 6 ft (Medium)',
      'Angle: 7 ft (Heavy)',
      'Angle: 7 ft (Medium)',
      'Angle: 8 ft (Heavy)',
      'Angle: 8 ft (Medium)'
    ],
    finishOptions: ['Industrial Grey']
  },
  {
    id: 'steel-rack-5tier-black',
    title: 'Steel Rack',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_rack_5tier_black.jpeg',
    description: 'A modern matte black coated 5-tier slotted angle steel rack. Strong structural design with fully adjustable shelving, suitable for home organizing or retail displays.',
    dimensions: 'Tray Rack: 3 × 1¾ ft / 3 × 1 ft / 4 × 1¾ ft / 4 × 1 ft (Heavy & Medium) | Slotted Angle Rack: 1 ft to 8 ft height (Heavy & Medium)',
    materials: 'Heavy-Duty Slotted Steel Angles, Black Powder Coated Finish',
    warranty: '1 Year Structural Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Tray: 3 x 1.75 ft (Heavy)',
      'Tray: 3 x 1.75 ft (Medium)',
      'Tray: 3 x 1 ft (Heavy)',
      'Tray: 3 x 1 ft (Medium)',
      'Tray: 4 x 1.75 ft (Heavy)',
      'Tray: 4 x 1.75 ft (Medium)',
      'Tray: 4 x 1 ft (Heavy)',
      'Tray: 4 x 1 ft (Medium)',
      'Angle: 1 ft (Heavy)',
      'Angle: 1 ft (Medium)',
      'Angle: 2 ft (Heavy)',
      'Angle: 2 ft (Medium)',
      'Angle: 3 ft (Heavy)',
      'Angle: 3 ft (Medium)',
      'Angle: 4 ft (Heavy)',
      'Angle: 4 ft (Medium)',
      'Angle: 5 ft (Heavy)',
      'Angle: 5 ft (Medium)',
      'Angle: 6 ft (Heavy)',
      'Angle: 6 ft (Medium)',
      'Angle: 7 ft (Heavy)',
      'Angle: 7 ft (Medium)',
      'Angle: 8 ft (Heavy)',
      'Angle: 8 ft (Medium)'
    ],
    finishOptions: ['Matte Black']
  },
  {
    id: 'steel-bookshelf-glass-blue',
    title: 'Steel Bookshelf',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_bookshelf_glass_blue.jpeg',
    description: 'A premium double-door steel almirah featuring four large clear glass panels for easy viewing. Ideal for libraries, office files, or showcasing decorative books.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'Cold Rolled Steel Sheet, Toughened Glass Panels',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Gloss Door: 36" x 19" x 6.5 ft (Heavy)',
      'Gloss Door: 42" x 19" x 6.5 ft (Heavy)',
      'Gloss Door: 36" x 19" x 5.5 ft (Heavy)'
    ],
    finishOptions: ['Sky Blue / White Frame', 'Classic Grey']
  },
  {
    id: 'steel-bookshelf-olive-4tier',
    title: 'Steel Bookshelf',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_bookshelf_olive_4tier.jpeg',
    description: 'A stylish olive green 4-tier steel library cabinet. Features swing-up, slide-in glass shutters for a sleek look and complete protection of your books from dust.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'High-Grade Steel Sheet, Slide-in Glass Mechanism',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Gloss Door: 36" x 19" x 6.5 ft (Heavy)',
      'Gloss Door: 42" x 19" x 6.5 ft (Heavy)',
      'Gloss Door: 36" x 19" x 5.5 ft (Heavy)'
    ],
    finishOptions: ['Olive Green', 'Ivory White']
  },
  {
    id: 'steel-bookshelf-grey-4tier',
    title: 'Steel Bookshelf',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_bookshelf_grey_4tier.jpeg',
    description: 'A standard classic grey 4-tier steel bookshelf with glass slide-up shutters. Features independent locks for secure storage of valuable books, journals, or files.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'Cold Rolled Steel, Powder Coated Grey, Slide-in Glass Shutters',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Gloss Door: 36" x 19" x 6.5 ft (Heavy)',
      'Gloss Door: 42" x 19" x 6.5 ft (Heavy)',
      'Gloss Door: 36" x 19" x 5.5 ft (Heavy)'
    ],
    finishOptions: ['Classic Grey', 'Office White']
  },
  {
    id: 'steel-locker-24door-orange',
    title: 'Steel Locker',
    category: 'Other Furniture',
    badge: 'badge-other',
    image: 'products/steel/steel_locker_24door_orange.jpeg',
    description: 'Multi-compartment storage unit with 24 individual lockable small lockers. Coated in a vibrant orange and blue finish. Ideal for gyms, staff rooms, schools, or warehouses.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'Heavy-Duty Sheet Metal, Key Locks',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Mobile Locker - 1 ft height (Heavy)',
      'Mobile Locker - 2 ft height (Heavy)',
      'Mobile Locker - 3 ft height (Heavy)',
      'Mobile Locker - 4 ft height (Heavy)',
      'Mobile Locker - 5 ft height (Heavy)',
      'Mobile Locker - 6 ft height (Heavy)'
    ],
    finishOptions: ['Orange and Blue Duo-tone']
  },
  {
    id: 'steel-locker-15door-teal',
    title: 'Steel Locker',
    category: 'Other Furniture',
    badge: 'badge-other',
    image: 'products/steel/steel_locker_15door_teal.jpeg',
    description: 'Multi-compartment steel storage locker unit with 15 individual key-lockable doors. Coated in a clean teal and white finish, perfect for staff storage or office safety.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'High-durability Steel Sheet, Key Locks',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Mobile Locker - 1 ft height (Heavy)',
      'Mobile Locker - 2 ft height (Heavy)',
      'Mobile Locker - 3 ft height (Heavy)',
      'Mobile Locker - 4 ft height (Heavy)',
      'Mobile Locker - 5 ft height (Heavy)',
      'Mobile Locker - 6 ft height (Heavy)'
    ],
    finishOptions: ['Teal and White Duo-tone']
  },
  {
    id: 'steel-filing-cabinet-4drawer',
    title: 'Steel Filing Cabinet',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_filing_cabinet_4drawer.jpeg',
    description: 'Heavy-duty vertical file organizer featuring 4 deep telescopic drawers with suspension file bars and a central lock system. Durable grey coat fits any standard office space.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'Cold Rolled Steel Sheet, Heavy-Duty Ball-Bearing Slides',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Steel File Cabinet - 5.5 ft height (Heavy)',
      'Steel File Cabinet - 4.5 ft height (Heavy)'
    ],
    finishOptions: ['Office Grey', 'Charcoal Black']
  },
  {
    id: 'other-rack-4tier-blue',
    title: 'Steel Rack',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/other_rack_4tier_blue.jpeg',
    description: 'A heavy-duty 4-tier steel storage rack finished in a high-gloss bright blue powder coat. Features adjustable shelves and safety red corner caps. Ideal for home garages, retail shops, or storage rooms.',
    dimensions: 'Tray Rack: 3 × 1¾ ft / 3 × 1 ft / 4 × 1¾ ft / 4 × 1 ft (Heavy & Medium) | Slotted Angle Rack: 1 ft to 8 ft height (Heavy & Medium)',
    materials: 'Heavy-Duty Cold Rolled Steel, Powder Coated Paint',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Tray: 3 x 1.75 ft (Heavy)',
      'Tray: 3 x 1.75 ft (Medium)',
      'Tray: 3 x 1 ft (Heavy)',
      'Tray: 3 x 1 ft (Medium)',
      'Tray: 4 x 1.75 ft (Heavy)',
      'Tray: 4 x 1.75 ft (Medium)',
      'Tray: 4 x 1 ft (Heavy)',
      'Tray: 4 x 1 ft (Medium)',
      'Angle: 1 ft (Heavy)',
      'Angle: 1 ft (Medium)',
      'Angle: 2 ft (Heavy)',
      'Angle: 2 ft (Medium)',
      'Angle: 3 ft (Heavy)',
      'Angle: 3 ft (Medium)',
      'Angle: 4 ft (Heavy)',
      'Angle: 4 ft (Medium)',
      'Angle: 5 ft (Heavy)',
      'Angle: 5 ft (Medium)',
      'Angle: 6 ft (Heavy)',
      'Angle: 6 ft (Medium)',
      'Angle: 7 ft (Heavy)',
      'Angle: 7 ft (Medium)',
      'Angle: 8 ft (Heavy)',
      'Angle: 8 ft (Medium)'
    ],
    finishOptions: ['Vibrant Blue with Red Accents']
  },
  {
    id: 'other-rack-5tier-woodboard',
    title: 'Steel Rack',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/other_rack_5tier_woodboard.jpeg',
    description: 'A premium modular storage rack featuring a sturdy matte black slotted steel frame and 5 high-density wood/MDF board shelf sheets. Offers adjustable shelf spacing and high load capacity.',
    dimensions: 'Tray Rack: 3 × 1¾ ft / 3 × 1 ft / 4 × 1¾ ft / 4 × 1 ft (Heavy & Medium) | Slotted Angle Rack: 1 ft to 8 ft height (Heavy & Medium)',
    materials: 'Slotted Steel Angle Frame, Laminated MDF Boards',
    warranty: '1 Year Structural Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Tray: 3 x 1.75 ft (Heavy)',
      'Tray: 3 x 1.75 ft (Medium)',
      'Tray: 3 x 1 ft (Heavy)',
      'Tray: 3 x 1 ft (Medium)',
      'Tray: 4 x 1.75 ft (Heavy)',
      'Tray: 4 x 1.75 ft (Medium)',
      'Tray: 4 x 1 ft (Heavy)',
      'Tray: 4 x 1 ft (Medium)',
      'Angle: 1 ft (Heavy)',
      'Angle: 1 ft (Medium)',
      'Angle: 2 ft (Heavy)',
      'Angle: 2 ft (Medium)',
      'Angle: 3 ft (Heavy)',
      'Angle: 3 ft (Medium)',
      'Angle: 4 ft (Heavy)',
      'Angle: 4 ft (Medium)',
      'Angle: 5 ft (Heavy)',
      'Angle: 5 ft (Medium)',
      'Angle: 6 ft (Heavy)',
      'Angle: 6 ft (Medium)',
      'Angle: 7 ft (Heavy)',
      'Angle: 7 ft (Medium)',
      'Angle: 8 ft (Heavy)',
      'Angle: 8 ft (Medium)'
    ],
    finishOptions: ['Matte Black / Wood Shelves']
  },
  {
    id: 'other-trolley-3tier-red',
    title: 'Steel Trolley',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/other_trolley_3tier_red.jpeg',
    description: 'A mobile steel utility cart equipped with 3 deep storage shelves, side grab handles, and 4 lockable caster wheels at the base. Coated in a durable bright red safety finish. Ideal for workshops, salons, offices, or kitchens.',
    dimensions: 'Tray Rack: 3 × 1¾ ft / 3 × 1 ft / 4 × 1¾ ft / 4 × 1 ft (Heavy & Medium) | Slotted Angle Rack: 1 ft to 8 ft height (Heavy & Medium)',
    materials: 'Heavy Gauge Steel Sheet, Industrial Caster Wheels',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    finishOptions: ['Safety Red']
  },
  {
    id: 'other-rack-5tier-grey',
    title: 'Steel Rack',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/other_rack_5tier_grey.jpeg',
    description: 'Commercial-grade slotted angle storage rack with 5 adjustable steel shelving levels. Offers heavy load-bearing capacity and a durable grey rust-proof finish. Ideal for industrial warehouses, store archives, or home storage.',
    dimensions: 'Tray Rack: 3 × 1¾ ft / 3 × 1 ft / 4 × 1¾ ft / 4 × 1 ft (Heavy & Medium) | Slotted Angle Rack: 1 ft to 8 ft height (Heavy & Medium)',
    materials: 'Industrial-Grade Angle Steel, Galvanized Hardwares',
    warranty: '1 Year Structural Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Tray: 3 x 1.75 ft (Heavy)',
      'Tray: 3 x 1.75 ft (Medium)',
      'Tray: 3 x 1 ft (Heavy)',
      'Tray: 3 x 1 ft (Medium)',
      'Tray: 4 x 1.75 ft (Heavy)',
      'Tray: 4 x 1.75 ft (Medium)',
      'Tray: 4 x 1 ft (Heavy)',
      'Tray: 4 x 1 ft (Medium)',
      'Angle: 1 ft (Heavy)',
      'Angle: 1 ft (Medium)',
      'Angle: 2 ft (Heavy)',
      'Angle: 2 ft (Medium)',
      'Angle: 3 ft (Heavy)',
      'Angle: 3 ft (Medium)',
      'Angle: 4 ft (Heavy)',
      'Angle: 4 ft (Medium)',
      'Angle: 5 ft (Heavy)',
      'Angle: 5 ft (Medium)',
      'Angle: 6 ft (Heavy)',
      'Angle: 6 ft (Medium)',
      'Angle: 7 ft (Heavy)',
      'Angle: 7 ft (Medium)',
      'Angle: 8 ft (Heavy)',
      'Angle: 8 ft (Medium)'
    ],
    finishOptions: ['Industrial Grey']
  },
  {
    id: 'other-rack-5tier-white',
    title: 'Steel Rack',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/other_rack_5tier_white.jpeg',
    description: 'A heavy-duty 5-tier storage shelving unit finished in a clean off-white / light grey powder coat. Features fully adjustable steel shelves and protective red corner feet. Perfect for clean rooms, pantries, offices, or home storage.',
    dimensions: 'Tray Rack: 3 × 1¾ ft / 3 × 1 ft / 4 × 1¾ ft / 4 × 1 ft (Heavy & Medium) | Slotted Angle Rack: 1 ft to 8 ft height (Heavy & Medium)',
    materials: 'Cold Rolled Slotted Steel, Powder Coated Clean Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Tray: 3 x 1.75 ft (Heavy)',
      'Tray: 3 x 1.75 ft (Medium)',
      'Tray: 3 x 1 ft (Heavy)',
      'Tray: 3 x 1 ft (Medium)',
      'Tray: 4 x 1.75 ft (Heavy)',
      'Tray: 4 x 1.75 ft (Medium)',
      'Tray: 4 x 1 ft (Heavy)',
      'Tray: 4 x 1 ft (Medium)',
      'Angle: 1 ft (Heavy)',
      'Angle: 1 ft (Medium)',
      'Angle: 2 ft (Heavy)',
      'Angle: 2 ft (Medium)',
      'Angle: 3 ft (Heavy)',
      'Angle: 3 ft (Medium)',
      'Angle: 4 ft (Heavy)',
      'Angle: 4 ft (Medium)',
      'Angle: 5 ft (Heavy)',
      'Angle: 5 ft (Medium)',
      'Angle: 6 ft (Heavy)',
      'Angle: 6 ft (Medium)',
      'Angle: 7 ft (Heavy)',
      'Angle: 7 ft (Medium)',
      'Angle: 8 ft (Heavy)',
      'Angle: 8 ft (Medium)'
    ],
    finishOptions: ['Off-White with Red Accents']
  },
  {
    id: 'wooden-wardrobe-3door-teak',
    title: 'Wooden Wardrobe',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_wardrobe_3door_teak.jpeg',
    description: 'A spacious 3-door wardrobe in a warm teak finish. Features beautiful natural wood grain swirls, secure key-lockable doors, and solid handles. Opens to reveal a large hanging section, drawers, and multiple shelves.',
    dimensions: '2 Door: 6½ ft × 32" × 15" / 3 Door: 6½ ft × 48" × 16"',
    materials: 'High-Grade Engineered Wood, Premium Teak Veneer & Polish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Standard: 54" x 22" x 78"',
      'Compact: 48" x 18" x 72"'
    ],
    finishOptions: ['Natural Teak', 'Warm Walnut', 'Dark Wenge']
  },
  {
    id: 'wooden-wardrobe-2door-teak-open',
    title: 'Wooden Wardrobe',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_wardrobe_2door_teak_open.jpeg',
    description: 'Detailed interior view of our 2-door wooden wardrobe. Showcases the premium organizational layout featuring a top metal hanging rod, two lockable drawers in the center, and spacious storage shelves.',
    dimensions: '2 Door: 6½ ft × 32" × 15" / 3 Door: 6½ ft × 48" × 16"',
    materials: 'High-Grade Engineered Wood, Premium Cabinet Hardware',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Standard: 36" x 22" x 78"',
      'Compact: 30" x 18" x 72"'
    ],
    finishOptions: ['Natural Teak', 'Warm Walnut', 'Dark Wenge']
  },
  {
    id: 'wooden-wardrobe-3door-teak-open',
    title: 'Wooden Wardrobe',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_wardrobe_3door_teak_open.jpeg',
    description: 'Detailed interior view of our 3-door wooden wardrobe. Showcases the double-sided hanging space, central locking drawers, and wide organizational shelves for efficient storage.',
    dimensions: '2 Door: 6½ ft × 32" × 15" / 3 Door: 6½ ft × 48" × 16"',
    materials: 'High-Grade Engineered Wood, Premium Cabinet Hardware',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Standard: 54" x 22" x 78"',
      'Compact: 48" x 18" x 72"'
    ],
    finishOptions: ['Natural Teak', 'Warm Walnut', 'Dark Wenge']
  },
  {
    id: 'wooden-wardrobe-walnut-collection',
    title: 'Wooden Wardrobe',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_wardrobe_walnut_collection.jpeg',
    description: 'A premium walnut finish wardrobe collection showing closed 2-door and open 2-door/3-door interior storage layouts. Built with heavy gauge engineered wood and finished in a sleek chocolate brown walnut laminate.',
    dimensions: 'Available in 2-Door and 3-Door models',
    materials: 'Heavy-Duty Compressed Wood, Scratch-Resistant Walnut Laminate',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      '2-Door Model (36" x 22" x 78")',
      '3-Door Model (54" x 22" x 78")'
    ],
    finishOptions: ['Warm Walnut', 'Classic Teak', 'Dark Wenge']
  },
  {
    id: 'wooden-wardrobe-luxury-wave',
    title: 'Wooden Wardrobe',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_wardrobe_luxury_wave.jpeg',
    description: 'A premium designer wardrobe featuring a striking hourglass wave pattern on the doors in silver, gold, and wood veneers. Includes round gold handles, soft-close hinges, and multiple drawer options.',
    dimensions: 'Available in 2-Door and 3-Door models',
    materials: 'Premium Wenge Wood Structure, Multi-Material Veneer Inlay',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: [
      '2-Door Model (36" x 22" x 78")',
      '3-Door Model (54" x 22" x 78")'
    ],
    finishOptions: ['Dark Wenge & Gold', 'Teak & Silver']
  },
  {
    id: 'wooden-mandir-ganesha-frosted',
    title: 'Wooden Pooja Mandir',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_mandir_ganesha_frosted.jpeg',
    description: 'A beautiful dark mahogany pooja mandir designed for home worship. Features frosted glass doors with elegant Ganesha prints, solid brass bells embedded in traditional arched carvings, spires, and two wide bottom storage drawers.',
    dimensions: '2.5 ft W x 1.5 ft D x 5 ft H',
    materials: 'Solid Seasoned Mahogany Wood, Brass Bells, Frosted Glass',
    warranty: '2 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Standard: 30" x 18" x 60"',
      'Grand: 36" x 22" x 72"'
    ],
    finishOptions: ['Mahogany Wood', 'Natural Teak', 'Dark Wenge']
  },
  {
    id: 'wooden-mandir-tree-of-life',
    title: 'Wooden Pooja Mandir',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    image: 'products/wooden_mandir_tree_of_life.jpeg',
    description: 'A stunning wenge finish wooden pooja mandir featuring an intricate Tree of Life cutout carving on the double doors. Decorated with brass hanging bells, three top spires, a middle drawer, and a lockable double-door cupboard at the base with gold Ganesha prints.',
    dimensions: '3 ft W x 1.8 ft D x 5.5 ft H',
    materials: 'Premium Teak Wood Frame, Brass Accents, Cutout Doors',
    warranty: '2 Years Structural Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Standard: 36" x 22" x 66"',
      'Compact: 30" x 18" x 60"'
    ],
    finishOptions: ['Dark Wenge', 'Natural Teak', 'Antique Polish']
  },
  {
    id: 'steel-almirah-magenta-single',
    title: 'Steel Almirah',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_almirah_magenta_single.jpeg',
    description: 'A premium single-door steel almirah featuring a vibrant magenta door with a built-in arched dressing mirror. Built with heavy-duty cold rolled steel and equipped with a high-security lock handle.',
    dimensions: 'Heavy: 42" × 19" × 6½ ft (75kg) / 36" × 19" × 6½ ft (63kg) | Medium: 42" × 19" × 6½ ft (65kg) / 36" × 19" × 6½ ft (52kg) | Lite: 34" × 17" × 6.6 ft (40kg) / 34" × 17" × 5½ ft (35kg) / 34" × 15" × 5½ ft (33kg) | 3-Door: 48" × 6½ ft / 60" × 6½ ft (90kg-110kg)',
    materials: 'High-Strength Sheet Metal, Arched Mirror Glass, Powder Coated Finish',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Heavy: 2.5 ft x 6.5 ft (30" x 19" x 78" - 55kg)',
      'Medium: 2 ft x 6.5 ft (24" x 19" x 78" - 45kg)',
      'Lite: 2 ft x 5.5 ft (24" x 15" x 66" - 35kg)'
    ],
    finishOptions: ['Magenta / Grey Frame', 'Wine Red / Grey Frame', 'Royal Blue / Grey Frame']
  },
  {
    id: 'steel-almirah-magenta-single-open',
    title: 'Steel Almirah',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_almirah_magenta_single_open.jpeg',
    description: 'Interior layout view of our single-door steel almirah. Showcases a highly functional 5-compartment vertical shelving design for organized storage of files, clothes, or valuables.',
    dimensions: 'Heavy: 42" × 19" × 6½ ft (75kg) / 36" × 19" × 6½ ft (63kg) | Medium: 42" × 19" × 6½ ft (65kg) / 36" × 19" × 6½ ft (52kg) | Lite: 34" × 17" × 6.6 ft (40kg) / 34" × 17" × 5½ ft (35kg) / 34" × 15" × 5½ ft (33kg) | 3-Door: 48" × 6½ ft / 60" × 6½ ft (90kg-110kg)',
    materials: 'High-Strength Sheet Metal, Heavy-Gauge Shelving, Powder Coated Finish',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Heavy: 2.5 ft x 6.5 ft (30" x 19" x 78" - 55kg)',
      'Medium: 2 ft x 6.5 ft (24" x 19" x 78" - 45kg)',
      'Lite: 2 ft x 5.5 ft (24" x 15" x 66" - 35kg)'
    ],
    finishOptions: ['Magenta / Grey Frame', 'Wine Red / Grey Frame', 'Royal Blue / Grey Frame']
  },
  {
    id: 'steel-almirah-copper-single-open',
    title: 'Steel Almirah',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_almirah_copper_single_open.jpeg',
    description: 'A premium single-door wardrobe finished in rich royal copper paint. Features a lockable center safe locker with a traditional motif, surrounded by wide deep shelving compartments.',
    dimensions: 'Heavy: 42" × 19" × 6½ ft (75kg) / 36" × 19" × 6½ ft (63kg) | Medium: 42" × 19" × 6½ ft (65kg) / 36" × 19" × 6½ ft (52kg) | Lite: 34" × 17" × 6.6 ft (40kg) / 34" × 17" × 5½ ft (35kg) / 34" × 15" × 5½ ft (33kg) | 3-Door: 48" × 6½ ft / 60" × 6½ ft (90kg-110kg)',
    materials: 'Heavy-Gauge Cold Rolled Steel, Secure Safe Lock, Powder Coated Finish',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Heavy: 2.5 ft x 6.5 ft (30" x 19" x 78" - 55kg)',
      'Medium: 2 ft x 6.5 ft (24" x 19" x 78" - 45kg)',
      'Lite: 2 ft x 5.5 ft (24" x 15" x 66" - 35kg)'
    ],
    finishOptions: ['Royal Copper', 'Golden Bronze', 'Office Grey']
  },
  {
    id: 'steel-almirah-colorful-collection',
    title: 'Steel Almirah',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    image: 'products/steel/steel_almirah_colorful_collection.jpeg',
    description: 'A collection of double-door steel almirahs featuring vibrant colors (Light Blue, Teal, Purple, Lavender, Royal Purple). Built with premium structural steel, multi-point lock systems, and glossy finishes.',
    dimensions: 'Heavy: 42" × 19" × 6½ ft (75kg) / 36" × 19" × 6½ ft (63kg) | Medium: 42" × 19" × 6½ ft (65kg) / 36" × 19" × 6½ ft (52kg) | Lite: 34" × 17" × 6.6 ft (40kg) / 34" × 17" × 5½ ft (35kg) / 34" × 15" × 5½ ft (33kg) | 3-Door: 48" × 6½ ft / 60" × 6½ ft (90kg-110kg)',
    materials: 'Heavy Gauge Structural Steel, Laminated Powder Coat',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Heavy: 42" x 19" x 6.5 ft (75kg)',
      'Heavy: 36" x 19" x 6.5 ft (63kg)',
      'Medium: 42" x 19" x 6.5 ft (65kg)',
      'Medium: 36" x 19" x 6.5 ft (52kg)',
      'Lite: 34" x 17" x 6.5 ft (40kg)',
      'Lite: 34" x 17" x 5.5 ft (35kg)',
      'Lite: 34" x 15" x 5.5 ft (33kg)'
    ],
    finishOptions: ['Lavender / Purple', 'Teal Green', 'Sky Blue', 'Royal Purple', 'Rose Pink']
  },
  {
    id: 'steel-locker-12door-orange',
    title: 'Steel Locker',
    category: 'Other Furniture',
    badge: 'badge-other',
    image: 'products/steel/steel_locker_12door_orange.jpeg',
    description: 'A multi-compartment vertical steel storage locker unit with 12 individual key-lockable orange doors arranged in a 2x6 configuration. Features a durable dark grey/charcoal frame.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'Heavy-Duty Cold Rolled Steel, Key Locks, Powder Coated Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Mobile Locker - 1 ft height (Heavy)',
      'Mobile Locker - 2 ft height (Heavy)',
      'Mobile Locker - 3 ft height (Heavy)',
      'Mobile Locker - 4 ft height (Heavy)',
      'Mobile Locker - 5 ft height (Heavy)',
      'Mobile Locker - 6 ft height (Heavy)'
    ],
    finishOptions: ['Orange & Charcoal Grey', 'Blue & White', 'Red & Grey']
  },
  {
    id: 'steel-locker-12door-orange-open',
    title: 'Steel Locker',
    category: 'Other Furniture',
    badge: 'badge-other',
    image: 'products/steel/steel_locker_12door_orange_open.jpeg',
    description: 'Detailed interior view of our 12-locker storage unit. Showcases the 12 deep square shelving compartments and solid steel door hinge construction.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'Heavy-Duty Cold Rolled Steel, Key Locks, Powder Coated Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Mobile Locker - 1 ft height (Heavy)',
      'Mobile Locker - 2 ft height (Heavy)',
      'Mobile Locker - 3 ft height (Heavy)',
      'Mobile Locker - 4 ft height (Heavy)',
      'Mobile Locker - 5 ft height (Heavy)',
      'Mobile Locker - 6 ft height (Heavy)'
    ],
    finishOptions: ['Orange & Charcoal Grey', 'Blue & White', 'Red & Grey']
  },
  {
    id: 'steel-locker-20door-yellow',
    title: 'Steel Locker',
    category: 'Other Furniture',
    badge: 'badge-other',
    image: 'products/steel/steel_locker_20door_yellow.jpeg',
    description: 'A spacious multi-compartment locker system with 20 individual key-lockable yellow doors arranged in a 4x5 layout. Coated in a durable light grey frame, ideal for warehouses, gyms, or schools.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'Heavy Gauge Structural Steel, Laminated Powder Coat',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Mobile Locker - 1 ft height (Heavy)',
      'Mobile Locker - 2 ft height (Heavy)',
      'Mobile Locker - 3 ft height (Heavy)',
      'Mobile Locker - 4 ft height (Heavy)',
      'Mobile Locker - 5 ft height (Heavy)',
      'Mobile Locker - 6 ft height (Heavy)'
    ],
    finishOptions: ['Yellow & Light Grey', 'Orange & Blue', 'Teal & White']
  },
  {
    id: 'steel-locker-24door-yellow-open',
    title: 'Steel Locker',
    category: 'Other Furniture',
    badge: 'badge-other',
    image: 'products/steel/steel_locker_24door_yellow_open.jpeg',
    description: 'Interior layout view of our 24-locker storage unit showing the 4x6 shelving layout. Showcases the double outer columns of open doors with individual locks.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'Heavy Gauge Structural Steel, Laminated Powder Coat',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Mobile Locker - 1 ft height (Heavy)',
      'Mobile Locker - 2 ft height (Heavy)',
      'Mobile Locker - 3 ft height (Heavy)',
      'Mobile Locker - 4 ft height (Heavy)',
      'Mobile Locker - 5 ft height (Heavy)',
      'Mobile Locker - 6 ft height (Heavy)'
    ],
    finishOptions: ['Yellow & Light Grey', 'Orange & Blue', 'Teal & White']
  },
  {
    id: 'steel-locker-6door-blue',
    title: 'Steel Locker',
    category: 'Other Furniture',
    badge: 'badge-other',
    image: 'products/steel/steel_locker_6door_blue.jpeg',
    description: 'Heavy-duty industrial 6-door steel locker featuring double-door compartments on 3 tiers. Coated in a vibrant blue finish with white frame accents. Central locking bars provide extra security.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'Industrial-Grade Cold Rolled Steel, central locking systems',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Mobile Locker - 1 ft height (Heavy)',
      'Mobile Locker - 2 ft height (Heavy)',
      'Mobile Locker - 3 ft height (Heavy)',
      'Mobile Locker - 4 ft height (Heavy)',
      'Mobile Locker - 5 ft height (Heavy)',
      'Mobile Locker - 6 ft height (Heavy)'
    ],
    finishOptions: ['Royal Blue & White', 'Charcoal & Grey', 'Olive Green & Ivory']
  },
  {
    id: 'steel-locker-6door-blue-open',
    title: 'Steel Locker',
    category: 'Other Furniture',
    badge: 'badge-other',
    image: 'products/steel/steel_locker_6door_blue_open.jpeg',
    description: 'Detailed interior view of our 6-compartment industrial steel locker. Shows 6 wide storage compartments, each equipped with two sub-shelves for clothing or office storage.',
    dimensions: 'Gloss Door: 36" × 19" × 6½ ft (Heavy) / 42" × 19" × 6½ ft (Heavy) / 36" × 19" × 5½ ft (Heavy) | Steel File Cabinet: 5.5 ft (Heavy) / 4.5 ft (Heavy) | Mobile Locker: 1 ft to 6 ft (Heavy)',
    materials: 'Industrial-Grade Cold Rolled Steel, Heavy-duty Shelves',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock',
    sizeOptions: [
      'Mobile Locker - 1 ft height (Heavy)',
      'Mobile Locker - 2 ft height (Heavy)',
      'Mobile Locker - 3 ft height (Heavy)',
      'Mobile Locker - 4 ft height (Heavy)',
      'Mobile Locker - 5 ft height (Heavy)',
      'Mobile Locker - 6 ft height (Heavy)'
    ],
    finishOptions: ['Royal Blue & White', 'Charcoal & Grey', 'Olive Green & Ivory']
  }
];
