/* ==========================================================================
   REAL PRODUCT CATALOG - Durga Furniture
   Replaces the old auto-generated placeholder products with the actual
   catalog supplied by the client (steel racks, almirahs, tables, cots,
   wooden furniture, and other items).
   ========================================================================== */

const productData = [
  // ---------------- STEEL FURNITURE : ALMIRAHS ----------------
  {
    id: 'steel-almirah-heavy',
    title: 'Steel Almirah - Heavy Duty',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 13500,
    originalPrice: 15500,
    image: 'products/steel_almirah.jpg',
    description: 'Rugged heavy-gauge steel almirah built for long-term daily use, with a full-height mirror door and multiple internal shelves for clothes and valuables.',
    dimensions: '42" W x 19" D x 6\' H (75kg) / 36" W x 19" D x 6\' H (63kg)',
    materials: 'Heavy Gauge Cold Rolled Steel, Powder Coated Finish',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-almirah-medium',
    title: 'Steel Almirah - Medium Duty',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 11500,
    image: 'products/almirah_purple.jpg',
    description: 'Balanced steel almirah offering strong storage capacity at a lighter weight, ideal for bedrooms and hostel rooms.',
    dimensions: '42" W x 19" D x 6\' H (65kg) / 36" W x 19" D x 6\' H (52kg)',
    materials: 'Cold Rolled Steel Sheet, Anti-Rust Powder Coating',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-almirah-lite',
    title: 'Steel Almirah - Lite',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 8500,
    image: 'products/almirah_lightblue_open.jpg',
    description: 'Lightweight and economical steel almirah with a full mirror shutter, adjustable shelves, and a smooth locking handle.',
    dimensions: '34" x 17" x 6\'6" (40kg) / 34" x 17" x 5\'6" (35kg) / 34" x 15" x 5\'6" (33kg)',
    materials: 'Mild Steel Sheet, Powder Coated Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-almirah-3door',
    title: '3 Door Steel Almirah',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 18500,
    image: 'products/almirah_darkblue.jpg',
    description: 'Extra-wide three-door steel almirah with generous locker space, perfect for large families or shared storage needs.',
    dimensions: '48" x 6\'.6" (90-110kg) / 60" x 6\'.6"',
    materials: 'Heavy Gauge Steel, Multi-Point Locking System',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-almirah-orange-locker',
    title: 'Steel Almirah - 3 Compartment Locker',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 15500,
    image: 'products/almirah_orange_open.jpg',
    description: 'Multi-compartment steel almirah with independently lockable sections, well suited for offices and shared accommodations.',
    dimensions: '48" x 6\' (1/2)',
    materials: 'Heavy Gauge Steel, Powder Coated Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-almirah-pink',
    title: 'Steel Almirah - Pink Mirror Door',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 9200,
    image: 'products/almirah_pink.jpg',
    description: 'Vibrant pink steel almirah with an arched mirror door design, a popular choice for bedrooms and girls hostels.',
    dimensions: '34"x17" x 6\'.6" (40kg) / 34"x17"x5\'(1/2) (35kg)',
    materials: 'Mild Steel Sheet, Powder Coated Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-almirah-maroon',
    title: 'Steel Almirah - Maroon Wood-Finish',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 9600,
    image: 'products/almirah_maroon.jpg',
    description: 'Wood-textured maroon finish steel almirah that blends the durability of steel with the warm look of wooden furniture.',
    dimensions: '42"x19" x 6\'(1/2) (65kg) / 36"x19"x6\'(1/2) (52kg)',
    materials: 'Cold Rolled Steel, Wood-Grain Powder Coating',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-almirah-blue-triple',
    title: 'Steel Almirah - Triple Locker Blue',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 16500,
    image: 'products/almirah_blue_triple_open.jpg',
    description: 'Three-shutter steel almirah with individual internal shelving and drawers, offering flexible organised storage.',
    dimensions: '48" x 6\'(1/2) (90kg to 110kg)',
    materials: 'Heavy Gauge Steel, Powder Coated Finish',
    warranty: '3 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-almirah-magenta',
    title: 'Steel Almirah - Slim Magenta Locker',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 7800,
    image: 'products/almirah_magenta_open.jpg',
    description: 'Compact single-door steel almirah, a space-saving option for small rooms and tight corners.',
    dimensions: '2\' x 6\' (1/2)',
    materials: 'Mild Steel Sheet, Powder Coated Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },

  // ---------------- STEEL FURNITURE : TABLES ----------------
  {
    id: 'steel-table-executive',
    title: 'Steel Executive Table',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 6500,
    image: 'products/steel_table_exec_white.jpg',
    description: 'Spacious executive office table with a wood-finish top on a sturdy steel frame with side storage cabinet.',
    dimensions: '4.5 ft x 2.5 ft',
    materials: 'Steel Frame, Laminated Wooden Top',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-table-heavy-drawers',
    title: 'Steel Heavy Table with Drawers',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 5800,
    image: 'products/steel_table_drawers_1.jpg',
    description: 'Heavy-duty steel office table fitted with a multi-drawer steel cabinet on one side for stationery and files.',
    dimensions: '4 ft x 2 ft',
    materials: 'Heavy Gauge Steel Frame, Wooden Top',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-table-blue-cabinet',
    title: 'Steel Office Table with Blue Cabinet',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 5200,
    image: 'products/steel_table_blue_cab.jpg',
    description: 'Compact steel office table with an attached lockable cabinet, ideal for study rooms and small offices.',
    dimensions: '3 ft x 2 ft',
    materials: 'Medium Gauge Steel Frame, Wooden Top',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-table-twin-workstation',
    title: 'Steel Twin Workstation Table',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 9500,
    image: 'products/steel_table_double.jpg',
    description: 'Back-to-back double workstation on a shared steel frame, built for offices needing space-efficient seating.',
    dimensions: '3 ft x 1.5 ft per seat',
    materials: 'Steel Frame, Laminated Wooden Top',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-table-plain',
    title: 'Plain Steel Table',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 3500,
    image: 'products/steel_table_plain.jpg',
    description: 'Simple, no-frills plain steel table, perfect for workshops, godowns, and utility spaces.',
    dimensions: '4 ft x 2 ft / 3 ft x 2 ft',
    materials: 'Mild Steel Frame, Wooden Top',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-table-office-plain',
    title: 'Steel Office Table - Medium',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 4200,
    image: 'products/steel_table_office_plain.jpg',
    description: 'Mid-size steel office table with a clean wooden top, sized for general office and study use.',
    dimensions: '3 ft x 1.5 ft',
    materials: 'Mild Steel Frame, Laminated Top',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-table-standard',
    title: 'Steel Table - Standard',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 3500,
    image: 'products/steel_table_thumb.jpg',
    description: 'Our best-selling standard steel table with a durable frame, suited for homes, shops, and offices alike.',
    dimensions: '4 ft x 2 ft',
    materials: 'Mild Steel Frame, Wooden Top',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },

  // ---------------- STEEL FURNITURE : RACKS ----------------
  {
    id: 'steel-rack-black',
    title: 'Steel Rack - Black 5-Tier',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 4200,
    image: 'products/steel_rack_black.jpg',
    description: 'Heavy-duty 5-shelf steel storage rack finished in matte black, ideal for godowns, shops, and warehouses.',
    dimensions: '3ft-4ft x 1ft-1.75ft, Heavy/Medium duty',
    materials: 'Angle Steel Frame, MDF/Steel Shelving',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-rack-white',
    title: 'Steel Rack - White 5-Tier',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 4500,
    image: 'products/steel_rack_white.jpg',
    description: 'Bright white 5-tier steel rack, great for retail displays and stockrooms needing a clean look.',
    dimensions: '3ft-4ft x 1ft-1.75ft, Heavy/Medium duty',
    materials: 'Angle Steel Frame, Powder Coated Shelving',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-rack-blue',
    title: 'Steel Rack - Blue 4-Tier',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 3800,
    image: 'products/steel_rack_blue.jpg',
    description: 'Compact 4-shelf steel rack in blue, well suited for home storage and small shop counters.',
    dimensions: '3ft x 1ft, Medium duty',
    materials: 'Angle Steel Frame, Steel Shelving',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-rack-dark',
    title: 'Steel Rack - Charcoal 5-Tier',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 4300,
    image: 'products/steel_rack_dark.jpg',
    description: 'Industrial-grade charcoal grey rack with 5 sturdy shelves for heavy load storage.',
    dimensions: '4ft x 1.75ft, Heavy duty',
    materials: 'Angle Steel Frame, MDF Shelving',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-rack-red',
    title: 'Steel Rack - Red 3-Tier',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 3200,
    image: 'products/steel_rack_red.jpg',
    description: 'Space-saving 3-shelf steel rack in red, a good fit for compact kitchens and utility corners.',
    dimensions: '3ft x 1.75ft, Medium duty',
    materials: 'Angle Steel Frame, Steel Shelving',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-rack-grey',
    title: 'Steel Rack - Grey 5-Tier',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 4000,
    image: 'products/steel_rack_grey.jpg',
    description: 'Versatile grey 5-tier steel rack designed for maximum storage in minimum footprint.',
    dimensions: '4ft x 1ft, Heavy/Medium duty',
    materials: 'Angle Steel Frame, Steel Shelving',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },

  // ---------------- STEEL FURNITURE : COTS ----------------
  {
    id: 'steel-cot-standard',
    sizeOptions: ['4 Feet', '5 Feet', '6 Feet'],
    mattressOptions: ['Without Mattress', 'Foam Mattress', 'Spring Mattress', 'Orthopedic Mattress'],
    title: 'Steel Cot - Round Motif',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 3500,
    image: 'products/steel_cot_thumb.jpg',
    description: 'Classic steel cot with a round motif headboard and footboard, finished in a durable matte coating.',
    dimensions: '4, 5, 6 Feet (Square Cot range)',
    materials: 'Mild Steel Tube Frame, Powder Coated Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-cot-double-black',
    sizeOptions: ['42 inch Heavy', '42 inch Medium'],
    mattressOptions: ['Without Mattress', 'Foam Mattress', 'Spring Mattress', 'Orthopedic Mattress'],
    title: 'Steel Cot - Double Bed Frame',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 6500,
    image: 'products/cot_black_double.jpg',
    description: 'Full-size double bed steel cot with a bold round-motif headboard, built for long-lasting daily use.',
    dimensions: '42 inch (Heavy/Medium)',
    materials: 'Mild Steel Tube Frame, Powder Coated Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-cot-mattress-combo',
    sizeOptions: ['44 inch Heavy'],
    mattressOptions: ['Foam Mattress Included', 'Upgrade to Spring Mattress', 'Upgrade to Orthopedic Mattress'],
    title: 'Steel Cot with Mattress Combo',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 7500,
    image: 'products/cot_with_mattress.jpg',
    description: 'Steel cot bundled with a matching mattress, ready to use straight out of the box.',
    dimensions: '44 inch (Heavy)',
    materials: 'Mild Steel Frame + Foam Mattress',
    warranty: '2 Years Frame Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-cot-single-shelf',
    sizeOptions: ['36 inch Heavy', '36 inch Medium'],
    mattressOptions: ['Without Mattress', 'Foam Mattress', 'Spring Mattress', 'Orthopedic Mattress'],
    title: 'Steel Cot - Single with Bookshelf Headboard',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 4200,
    image: 'products/cot_single_shelf.jpg',
    description: 'Space-saving single steel cot with a built-in bookshelf headboard, great for hostels and children\u2019s rooms.',
    dimensions: '36 inch (Heavy/Medium)',
    materials: 'Mild Steel Tube Frame, Powder Coated Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-cot-blue-mattress',
    sizeOptions: ['30 inch Heavy', '30 inch Medium'],
    mattressOptions: ['Foam Mattress Included', 'Upgrade to Spring Mattress', 'Upgrade to Orthopedic Mattress'],
    title: 'Steel Cot - Blue Mattress Set',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 7800,
    image: 'products/cot_blue_mattress.jpg',
    description: 'Elegant arched-headboard steel cot paired with a blue quilted mattress for a complete bedroom set.',
    dimensions: '30 inch (Heavy/Medium)',
    materials: 'Mild Steel Frame + Foam Mattress',
    warranty: '2 Years Frame Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-cot-bunker',
    sizeOptions: ['2.5 Feet', '3 Feet'],
    mattressOptions: ['Without Mattress', 'Foam Mattress', 'Spring Mattress', 'Orthopedic Mattress'],
    title: 'Steel Bunker Cot',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 6500,
    image: 'products/cot_bunker.jpg',
    description: 'Double-decker bunker cot built from steel tubing, a space-efficient choice for hostels and shared rooms.',
    dimensions: '2.5 Feet / 3 Feet (Heavy)',
    materials: 'Mild Steel Tube Frame, Powder Coated Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'steel-cot-folding',
    sizeOptions: ['4 Feet Heavy', '4 Feet Medium'],
    mattressOptions: ['Without Mattress', 'Foam Mattress'],
    title: 'Steel Folding Camp Cot',
    category: 'Steel Furniture',
    badge: 'badge-steel',
    price: 2200,
    image: 'products/cot_folding_green.jpg',
    description: 'Portable folding steel cot with fabric bedding surface, easy to store and carry for guests or camps.',
    dimensions: 'Ordinary Cot 4" feet (Heavy/Medium)',
    materials: 'Mild Steel Frame, Woven Fabric Surface',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },

  // ---------------- WOODEN FURNITURE ----------------
  {
    id: 'wooden-dressing-table-mirror',
    title: 'Wooden Dressing Table - Mirror Cabinet',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 8500,
    image: 'products/dressing_table_1.jpg',
    description: 'Tall wooden dressing table with a full-length mirror and side storage cabinet, finished in a rich wood tone.',
    dimensions: '66" H x 24" W x 16" D',
    materials: 'Engineered Wood, Mirror Glass',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-dressing-table-compact',
    title: 'Wooden Dressing Table - Compact with Stool',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 7200,
    image: 'products/dressing_table_2.jpg',
    description: 'Compact dressing table with a fold-away stool, well suited for smaller bedrooms.',
    dimensions: '30" H x 28" W x 16" D',
    materials: 'Engineered Wood, Mirror Glass',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-dressing-table-ornate',
    title: 'Wooden Dressing Table - Ornate Carved',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 9500,
    image: 'products/dressing_table_3.jpg',
    description: 'Intricately carved wooden dressing table with a decorative mirror frame, a statement piece for master bedrooms.',
    dimensions: '68" H x 26" W x 18" D',
    materials: 'Solid Wood, Carved Detailing, Mirror Glass',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-dressing-wardrobe',
    title: 'Wooden Dressing Wardrobe',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 15500,
    image: 'products/dressing_wardrobe.jpg',
    description: 'Combined wardrobe and dressing unit with a full mirror door and ample hanging and shelf space.',
    dimensions: '75" H x 40" W x 20" D',
    materials: 'Engineered Wood, Laminate Finish, Mirror Glass',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-wardrobe-3door',
    title: '3 Door Wooden Wardrobe',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 19500,
    image: 'products/3door_wardrobe.jpg',
    description: 'Spacious 3-door wooden wardrobe with a mix of hanging space, shelves, and drawers for full family storage.',
    dimensions: '75" H x 54" W x 21" D',
    materials: 'Engineered Wood, Wood Veneer Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-wardrobe-6door',
    title: '6 Door Wooden Wardrobe',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 24500,
    image: 'products/6door_wardrobe.jpg',
    description: 'Large 6-door wardrobe with a striking two-tone finish, offering maximum storage for bigger bedrooms.',
    dimensions: '75" H x 72" W x 21" D',
    materials: 'Engineered Wood, Wood Veneer Finish',
    warranty: '2 Years Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-wardrobe-2door',
    title: 'Wooden Wardrobe - 2 Door',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 12500,
    image: 'products/wardrobe_wooden.jpg',
    description: 'Simple and functional 2-door wooden wardrobe with a warm honey finish, suitable for any bedroom.',
    dimensions: '75" H x 36" W x 21" D',
    materials: 'Engineered Wood, Laminate Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-wardrobe-natural',
    title: 'Wooden Wardrobe - Natural Finish',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 13500,
    image: 'products/wardrobe_thumb.jpg',
    description: 'Wardrobe finished in a natural wood tone with sliding panel doors, blending easily into most interiors.',
    dimensions: '75" H x 40" W x 21" D',
    materials: 'Engineered Wood, Natural Wood Laminate',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-shoe-stand',
    title: 'Wooden Shoe Stand Cabinet',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 6200,
    image: 'products/shoe_stand_wood.jpg',
    description: 'Enclosed wooden shoe cabinet with multiple compartments to keep footwear tidy and dust-free.',
    dimensions: '36" H x 30" W x 14" D',
    materials: 'Engineered Wood, Laminate Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-tv-stand-storage',
    title: 'Wooden TV Stand with Storage',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 8800,
    image: 'products/tv_stand_1.jpg',
    description: 'Wide TV entertainment unit with open shelves and a drawer, designed to hold a TV plus set-top boxes and media.',
    dimensions: '24" H x 55" W x 16" D',
    materials: 'Engineered Wood, Laminate Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-tv-unit-maroon',
    title: 'Wooden TV Unit - Maroon Finish',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 10500,
    image: 'products/tv_stand_3.jpg',
    description: 'Tall wall-style TV unit in a rich maroon finish with a backlit display niche and closed cabinet storage.',
    dimensions: '48" H x 60" W x 16" D',
    materials: 'Engineered Wood, High Gloss Laminate',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-computer-table',
    title: 'Wooden Computer Table',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 6500,
    image: 'products/computer_tables.jpg',
    description: 'Practical wooden computer table with a keyboard tray and side drawers for a compact home workstation.',
    dimensions: '30" H x 40" W x 20" D',
    materials: 'Engineered Wood, Laminate Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-office-table-drawer',
    title: 'Wooden Office Table with Drawer',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 7200,
    image: 'products/office_table_wood_1.jpg',
    description: 'Study/office table in a warm wood finish with a side drawer and cupboard for stationery storage.',
    dimensions: '30" H x 42" W x 22" D',
    materials: 'Engineered Wood, Laminate Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-office-table-compact',
    title: 'Wooden Office Table - Compact',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 6800,
    image: 'products/office_table_wood_2.jpg',
    description: 'Slim wooden office table with a single side drawer, sized for tighter office and study spaces.',
    dimensions: '30" H x 36" W x 20" D',
    materials: 'Engineered Wood, Laminate Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-multipurpose-table',
    title: 'Wooden Multipurpose Table',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 5800,
    image: 'products/multipurpose_table_1.jpg',
    description: 'Versatile open-shelf wooden table that doubles as a study desk, display unit, or side console.',
    dimensions: '30" H x 30" W x 18" D',
    materials: 'Engineered Wood, Laminate Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-multipurpose-corner-table',
    title: 'Wooden Corner Multipurpose Table',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 6200,
    image: 'products/multipurpose_table_2.jpg',
    description: 'L-shaped corner table with a mix of open cubbies and a work surface, ideal for compact study corners.',
    dimensions: '30" H x 36" W x 30" D',
    materials: 'Engineered Wood, Laminate Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-bookshelf',
    title: 'Wooden Book Shelf Cabinet',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 9500,
    image: 'products/book_shelves_wooden.jpg',
    description: 'Glass-door wooden bookshelf with multiple tiers, keeping books and display items dust-free and organised.',
    dimensions: '60" H x 30" W x 14" D',
    materials: 'Engineered Wood, Glass Panel Doors',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-cot-carved',
    sizeOptions: ['Queen (5 Feet)', 'King (6 Feet)'],
    mattressOptions: ['Without Mattress', 'Foam Mattress', 'Spring Mattress', 'Orthopedic Mattress'],
    finishOptions: ['Natural Teak', 'Walnut', 'Mahogany', 'Rosewood'],
    title: 'Wooden Cot - Carved Headboard',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 22500,
    image: 'products/wooden_cot.jpg',
    description: 'Solid wood double cot with an ornately carved headboard, bringing a traditional, handcrafted look to the bedroom.',
    dimensions: '42" H (headboard) x 75" L x 60" W',
    materials: 'Solid Seasoned Wood, Carved Detailing',
    warranty: '5 Years Structural Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-sofa-set',
    title: 'Wooden Sofa Set',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 28500,
    image: 'products/sofa_thumb.jpg',
    description: 'Two-seater wooden sofa set with slatted armrests and backrest, finished with a smooth natural wood tone.',
    dimensions: '34" H x 76" W x 32" D',
    materials: 'Seasoned Solid Wood',
    warranty: '3 Years Structural Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-center-table',
    title: 'Wooden Center Table',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 5500,
    image: 'products/center_table.jpg',
    description: 'Sturdy wooden centre table with a laser-cut geometric side panel design, a good match for living room sofa sets.',
    dimensions: '18" H x 40" W x 20" D',
    materials: 'Solid Wood',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'wooden-teapoy',
    title: 'Wooden Teapoy',
    category: 'Wooden Furniture',
    badge: 'badge-wooden',
    price: 3800,
    image: 'products/teapoy.jpg',
    description: 'Round wooden teapoy with curved legs, a compact accent table for tea sets and living room decor.',
    dimensions: '20" H x 24" Diameter',
    materials: 'Solid Wood',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },

  // ---------------- OTHER FURNITURE ----------------
  {
    id: 'plastic-chair',
    title: 'Plastic Chair',
    category: 'Other Furniture',
    badge: 'badge-other',
    price: 450,
    image: 'products/plastic_chair.jpg',
    description: 'Durable, stackable plastic chair for everyday use at home, functions, and outdoor seating.',
    dimensions: '32" H x 18" W x 20" D',
    materials: 'High-Density Polypropylene',
    warranty: '6 Months Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'pooja-stand',
    title: 'Pooja Stand - Wall Mount',
    category: 'Other Furniture',
    badge: 'badge-other',
    price: 4500,
    image: 'products/pooja_stand.jpg',
    description: 'Compact wall-mounted pooja stand with a decorative back panel, doors, and a hanging bell to complete the look.',
    dimensions: '30" H x 24" W x 12" D',
    materials: 'Engineered Wood, Laminate Finish',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'premium-mattress',
    title: 'Premium Mattress',
    category: 'Other Furniture',
    badge: 'badge-other',
    price: 5500,
    image: 'products/mattresses.jpg',
    description: 'Comfortable, supportive mattress suited for daily use, available to match your steel or wooden cot size.',
    dimensions: 'Customisable to 4, 5, or 6 Feet cots',
    materials: 'High-Density Foam, Quilted Fabric Cover',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'roller-office-chair',
    title: 'Ergonomic Roller Office Chair',
    category: 'Other Furniture',
    badge: 'badge-other',
    price: 4800,
    image: 'products/roller_chair.jpg',
    description: 'Mesh-back ergonomic office chair with adjustable height, armrests, and smooth-rolling caster wheels.',
    dimensions: '40"-44" H (adjustable) x 24" W x 24" D',
    materials: 'Mesh Fabric, Steel Base, PU Wheels',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  },
  {
    id: 'glass-dining-table',
    title: 'Glass-Top Dining Table Set',
    category: 'Other Furniture',
    badge: 'badge-other',
    price: 12500,
    image: 'products/dining_table_thumb.jpg',
    description: 'Round glass-top dining table on a decorative metal base, paired with matching chairs for compact dining spaces.',
    dimensions: '30" H x 36" Diameter',
    materials: 'Tempered Glass Top, Powder Coated Metal Base',
    warranty: '1 Year Manufacturing Warranty',
    availability: 'In Stock'
  }
];
